---
- hosts: all
  tasks:
    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 600

    - name: Install curl
      apt:
        name: curl
        state: present
