---
name: CI

"on":
  pull_request:
  push:
    branches-ignore:
      - "dependabot/**"
  schedule:
    - cron: "22 15 * * 3"
  workflow_dispatch:

defaults:
  run:
    working-directory: metabrainz.haproxy

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: metabrainz.haproxy

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip3 install yamllint ansible ansible-lint

      - name: Run lint
        run: |
          yamllint .
          ansible-lint

  test:
    name: py:${{ matrix.python }} ansible:${{ matrix.ansible }} os:${{ matrix.distro }}
    runs-on: ubuntu-latest
    needs:
      - lint
    strategy:
      matrix:
        python:
          - "3.10"
          - "3.11"
        ansible:
          - 5
          - 6
          - 7
        distro:
          - ubuntu2004
          - ubuntu2204
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3
        with:
          path: metabrainz.haproxy

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Cache pip directory
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-ansible${{ matrix.ansible }}-py${{ matrix.python }}-v1

      - name: Install test dependencies
        run: >-
          pip3 install
          'ansible==${{ matrix.ansible }}.*'
          'docker==6.*'
          'molecule-plugins[docker]'
          'urllib3<2.0'

      - name: Run pip freeze
        run: pip3 freeze --all

      - name: Run tests
        run: molecule test
        env:
          ANSIBLE_FORCE_COLOR: 1
          PY_COLORS: 1
          MOLECULE_DISTRO: ${{ matrix.distro }}
